name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test ${{ matrix.channel }}:${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["", "1.12.x", "1.2.1"]
        channel: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - run: dart --version
  main:
    name: "Test main: on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@master
        with:
          channel: main
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Test Flutter App
        run: flutter test
      - name: Biuld Flutter APK
        run: flutter build Android APK
      - name: BUild Flutter IOS App
        run: flutter build ios --release --no-codesign
        # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
